version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
  
  spark:
    image: sfps-spark
    ports:
      - "8080:8080"
    volumes:
      - "exchange:/exchange"
  
  server:
    image: sfps-server
    ports:
      - "8088:8088"
    volumes:
      - "exchange:/exchange"

volumes:

  exchange:
    driver: local
     
  # db_loader: 
  #   ...
  #   links:
  #     - db
# volumes:
#   grafana_config:
#     driver: local
