package sfps.types

import sfps.types._
import sfps.etl._


object Mappers {

    val NONE = -99999999;
    def doubleTypedMapper(x: Schema.DataRow) : DoubleTypedDatasetRow = {
        DoubleTypedDatasetRow(
            x._1.id,
            x._2.deviceMatch.toDouble.getOrElse(NONE),
            x._2.factorCodes.toDouble.getOrElse(NONE),
            x._2.firstEncounter.toDouble.getOrElse(NONE),
            x._2.icAddress.toDouble.getOrElse(NONE),
            x._2.icInternet.toDouble.getOrElse(NONE),
            x._2.icSuspicious.toDouble.getOrElse(NONE),
            x._2.icVelocity.toDouble.getOrElse(NONE),
            x._2.icidentity.toDouble.getOrElse(NONE),
            x._2.ipRoutingMethod.toDouble.getOrElse(NONE),
            x._2.reasonCode.toDouble().getOrElse(NONE),
            x._2.timeOnPage.toDouble().getOrElse(NONE),
            x._2.pp_1.toDouble().getOrElse(NONE),
            x._2.pp_30.toDouble().getOrElse(NONE),
            x._2.pp_60.toDouble().getOrElse(NONE),
            x._2.pp_90.toDouble().getOrElse(NONE),
            x._3.countryCode.toDouble.getOrElse(NONE),
            x._3.countryFrom.toDouble().getOrElse(NONE),
            x._3.countryTo.toDouble().getOrElse(NONE),
            x._3.distance_to_arrival.toDouble.getOrElse(NONE),  
            x._3.distance_to_departure.toDouble().getOrElse(NONE),
            x._3.iataFrom.toDouble().getOrElse(NONE),
            x._3.iataTo.toDouble().getOrElse(NONE),
            x._3.ip_city.toDouble().getOrElse(NONE),
            x._3.lagTimeHours.toDouble().getOrElse(NONE),
            x._3.speed_to_departure.toDouble().getOrElse(NONE),
            x._3.triangulation_height.toDouble().getOrElse(NONE),
            x._3.triangulation_height_speed.toDouble().getOrElse(NONE),
            x._3.trip_distance.toDouble().getOrElse(NONE),
            x._4.mai_score.toDouble().getOrElse(NONE),
            x._4.mai_advice.toDouble().getOrElse(NONE),
            x._4.mai_verification.toDouble().getOrElse(NONE),
            x._4.mai_reason.toDouble().getOrElse(NONE),
            x._4.mai_risk.toDouble().getOrElse(NONE),
            x._4.mai_status.toDouble().getOrElse(NONE),
            x._4.mai_unique.toDouble().getOrElse(NONE),
            x._4.mai_avg_secs.toDouble().getOrElse(NONE),
            x._4.mai_buys.toDouble().getOrElse(NONE),
            x._4.mai_searches.toDouble().getOrElse(NONE),
            x._4.mai_pax.toDouble().getOrElse(NONE),
            x._4.mai_type.toDouble().getOrElse(NONE),
            x._4.mai_rels.toDouble().getOrElse(NONE),
            x._4.mai_app.toDouble().getOrElse(NONE),
            x._5.mai_urgency.toDouble().getOrElse(NONE),
            x._5.mai_network.toDouble().getOrElse(NONE),
            x._5.mai_all_pax.toDouble().getOrElse(NONE),
            x._5.mai_last_secs.toDouble().getOrElse(NONE),
            x._5.mai_language.toDouble().getOrElse(NONE),
            x._5.mai_negative.toDouble().getOrElse(NONE),
            x._5.mai_suspect.toDouble().getOrElse(NONE),
            x._5.mai_os.toDouble().getOrElse(NONE),
            x._5.mai_policy_score.toDouble().getOrElse(NONE),
            x._5.mai_pulevel.toDouble().getOrElse(NONE),
            x._5.mai_city.toDouble().getOrElse(NONE),
            x._5.mai_region.toDouble().getOrElse(NONE),
            x._5.maibis_score.toDouble().getOrElse(NONE),
            x._5.maibis_reason.toDouble().getOrElse(NONE),
            x._5.maitris_score.toDouble().getOrElse(NONE),
            x._6.online_airport_state.toDouble.getOrElse(NONE),
            x._6.online_billing_address_state.toDouble.getOrElse(NONE),
            x._6.online_cep_number_bond.toDouble.getOrElse(NONE),
            x._6.online_city_bond.toDouble.getOrElse(NONE),
            x._6.online_ddd.toDouble.getOrElse(NONE),
            x._6.online_ddd_bond.toDouble.getOrElse(NONE),
            x._6.online_death.toDouble.getOrElse(NONE),
            x._6.online_email.toDouble.getOrElse(NONE),
            x._6.online_family_bond.toDouble.getOrElse(NONE),
            x._6.online_ip_state.toDouble.getOrElse(NONE),
            x._6.online_name.toDouble.getOrElse(NONE),
            x._6.online_phone.toDouble.getOrElse(NONE),
            x._6.online_queries.toDouble.getOrElse(NONE),
            x._6.online_state_bond.toDouble.getOrElse(NONE),
            x._7.billingCountryCode.toDouble.getOrElse(NONE),
            x._7.cancelled.toDouble.getOrElse(NONE),
            x._7.cardCountryCode.toDouble.getOrElse(NONE),
            x._7.totalUsdAmount.toDouble.getOrElse(NONE),
            x._7.paymentsCardType.toDouble.getOrElse(NONE),
            x._7.paymentsInstallments.toDouble.getOrElse(NONE),
            x._8.caseDate.toDouble.getOrElse(NONE),
            x._8.case_minutes_distance.toDouble.getOrElse(NONE),
            x._8.cases_count.toDouble.getOrElse(NONE),
            x._8.channel.toDouble.getOrElse(NONE),
            x._8.correl_id.toDouble.getOrElse(NONE),
            x._8.count_different_cards.toDouble.getOrElse(NONE),
            x._8.count_different_installments.toDouble.getOrElse(NONE),
            x._8.domain_proc.toDouble.getOrElse(NONE),
            x._8.eulerBadge.toDouble.getOrElse(NONE),
            x._8.friendly.toDouble.getOrElse(NONE),
            x._8.hours_since_first_verification.toDouble.getOrElse(NONE),
            x._8.many_holders_for_card.toDouble.getOrElse(NONE),
            x._8.many_names_for_document.toDouble.getOrElse(NONE),
            x._8.same_field_features.toDouble.getOrElse(NONE),
            
            x._9.apocrypha.toDouble().getOrElse(NONE)
          )

    }
}